version: "3.9"
services:
  app:
    build: .
    container_name: quiz-backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
  db:
    image: postgres:16
    container_name: quiz-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quizdb
    ports:
      - "5432:5432"
