version: "3.9"
services:
  app:
    build: .
    container_name: quiz-backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    # Remove volumes in production - they're for development only
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    restart: unless-stopped
    
  db:
    image: postgres:16
    container_name: quiz-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quizdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d quizdb"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
